// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reguistro_Completo.DAL;

namespace Reguistro_Completo.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20210301041933_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("Reguistro_Completo.Entidades.Permiso", b =>
                {
                    b.Property<int>("PermisoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetallePermiso")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PermisosID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("VecesAsignado")
                        .HasColumnType("INTEGER");

                    b.HasKey("PermisoID");

                    b.HasIndex("PermisosID");

                    b.ToTable("MyProperty");

                    b.HasData(
                        new
                        {
                            PermisoID = 1,
                            Descripcion = "Producto en venta",
                            DetallePermiso = "Descuento",
                            Nombre = "Papita",
                            VecesAsignado = false
                        },
                        new
                        {
                            PermisoID = 2,
                            Descripcion = "Vendedor en puesto",
                            DetallePermiso = "Venta",
                            Nombre = "Juan",
                            VecesAsignado = false
                        },
                        new
                        {
                            PermisoID = 3,
                            Descripcion = "Cobradora en turno",
                            DetallePermiso = "Cobrar",
                            Nombre = "Paola",
                            VecesAsignado = false
                        });
                });

            modelBuilder.Entity("Reguistro_Completo.Entidades.Roles", b =>
                {
                    b.Property<int>("RolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("esActivo")
                        .HasColumnType("INTEGER");

                    b.HasKey("RolID");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Reguistro_Completo.Entidades.RolesDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PermisoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RolID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("esAsignado")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RolID");

                    b.ToTable("RolesDetalle");
                });

            modelBuilder.Entity("Reguistro_Completo.Entidades.Usuario", b =>
                {
                    b.Property<int>("UsuarioID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alias")
                        .HasColumnType("TEXT");

                    b.Property<string>("Clave")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombres")
                        .HasColumnType("TEXT");

                    b.Property<string>("RolID")
                        .HasColumnType("TEXT");

                    b.HasKey("UsuarioID");

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("Reguistro_Completo.Entidades.Permiso", b =>
                {
                    b.HasOne("Reguistro_Completo.Entidades.Permiso", "permisos")
                        .WithMany()
                        .HasForeignKey("PermisosID");

                    b.Navigation("permisos");
                });

            modelBuilder.Entity("Reguistro_Completo.Entidades.RolesDetalle", b =>
                {
                    b.HasOne("Reguistro_Completo.Entidades.Roles", null)
                        .WithMany("Detalles")
                        .HasForeignKey("RolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Reguistro_Completo.Entidades.Usuario", b =>
                {
                    b.HasOne("Reguistro_Completo.Entidades.Roles", "Rol")
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Reguistro_Completo.Entidades.Roles", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
